version: "3.8"

services:
  fastapi:
    container_name: ecac04-fastapi
    build:
      context: .
      dockerfile: fastapi.Dockerfile
    ports:
      - "8000:80"
  nginx:
    image: nginx
    depends_on:
      - fastapi
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/letsencrypt
